import Navbar, { NavbarTab } from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { ReactQueryProvider } from "@/components/queryprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "TDL",
    description: "Generated by create next app",
};

const tabs: NavbarTab[] = [
    {
        page_id: "medlog",
        title: "Health",
        redirect: "/medlog",
    },
    {
        page_id: "tasks",
        title: "Tasks",
        redirect: "/",
    },
];

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={
                    inter.className + " flex flex-col h-[100vh] w-[100vw]"
                }
            >
                <ReactQueryProvider>
                    <Navbar tabs={tabs}></Navbar>
                    <main className="grow">{children}</main>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
