#!/usr/bin/env python3
"""
Temporary solution for https://github.com/Microsoft/vscode/issues/15909
"""
import json
import logging
import os
import pathlib
from copy import deepcopy
import re

sub_workspaces = ["server", "client"]

trailingcommas = lambda s: re.sub(r",\n\s*?}", "\n}", s)
singlecomment = lambda s: re.sub(r"\/\/.+?\n", "\n", s)
# nesting doesnt work
multicomment = lambda s: re.sub(r"\/\*.+?\*\/", "\n", s, flags=re.S)

# standardise path
if str(pathlib.Path(os.curdir).resolve()).split("/")[-1] == "utils":
    os.chdir("..")

path = pathlib.Path(".vscode/settings.json")
if not path.exists():
    logging.warning("Nothing to inherit.")
    quit()

with open(path) as f:
    # remove trailing commas
    text = trailingcommas(singlecomment(multicomment(f.read())))
    try:
        default = json.loads(text)
    except Exception as e:
        print(
            f"Error attempting read on {path.resolve()}. If you aren't getting errors, check comments and trailing commas."
        )
        raise e

for i in sub_workspaces:
    subpath = pathlib.Path(f"{i}/.vscode/settings.json")
    new = deepcopy(default)
    if subpath.exists():
        with open(subpath) as f:
            # python's update function is the entire method of inheritance with this
            if settings := json.load(f):
                new.update(settings)
            if new == settings:
                logging.info(f"Nothing to change in {i}.")
                continue
    else:
        os.mkdir("/".join(str(subpath).split("/")[:-1]))

    print(new)
    if input("Overwrite? [Type nothing to proceed]"):
        print("Skipping")
        continue

    with open(subpath, "w") as f:
        json.dump(new, f)
